export const AGREEMENTS_FETCH_LIST = 'AGREEMENTS_FETCH_LIST';
export const AGREEMENTS_CREATE = 'AGREEMENTS_CREATE';
export const AGREEMENTS_ADD_LIST = 'AGREEMENTS_ADD_LIST';
export const AGREEMENTS_APPEND = 'AGREEMENTS_APPEND'
export const AGREEMENTS_CARDS_CLEAR = 'AGREEMENTS_CARDS_CLEAR';
export const SET_COUNT_NEXT_PAGE = 'AGREEMENTS_SET_COUNT_NEXT_PAGE';
